### ISSUE TITLE
build issue: BlockingIOError: write could not complete without blocking

### ISSUE THREAD

**Issue by rth** [iodide-project/pyodide#1059]
When building the pre-built docker image for 0.16.1 with,
```
git checkout 0.16.1
docker build -t iodide/pyodide:0.16.1 -f Dockerfile-prebuilt --build-arg VERSION=0.16.1 .
```
I consistently get the following exception,

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/src/pyodide/pyodide_build/__main__.py", line 34, in <module>
    main()
  File "/src/pyodide/pyodide_build/__main__.py", line 28, in main
    args.func(args)
  File "/src/pyodide/pyodide_build/buildall.py", line 316, in main
    build_packages(packages_dir, outputdir, args)
  File "/src/pyodide/pyodide_build/buildall.py", line 212, in build_packages
    build_from_graph(pkg_map, outputdir, args)
  File "/src/pyodide/pyodide_build/buildall.py", line 198, in build_from_graph
    raise pkg
  File "/src/pyodide/pyodide_build/buildall.py", line 181, in builder
    pkg.build(outputdir, args)
  File "/src/pyodide/pyodide_build/buildall.py", line 76, in build
    shutil.copyfileobj(f, sys.stdout)
  File "/usr/local/lib/python3.8/shutil.py", line 205, in copyfileobj
    fdst_write(buf)
BlockingIOError: [Errno 11] write could not complete without blocking
```

Redirecting to a file doesn't help. I think it's some issue due to the combination of Docker + use of `shutil.copyfileobj` to redirect log to stdout, but haven't had time to look in more detail.

**Edit:** I was running in a tmux on a remote machine via SSH, so maybe that could also have something to do with it.

**Comment by rth** [comment]
The issue seem to be output stream capacity, so cherry-picking https://github.com/iodide-project/pyodide/pull/947 on top of 0.16.1 would certainly fix the issue. Haven't seen many workarounds short of reducing the verbosity, so I'll probably do that. Even if it's not strictly 0.16.1
