### ISSUE TITLE
numpy import failure in _cblas_caxpy

### ISSUE THREAD

**Issue by rth** [iodide-project/pyodide#115]
When building pyodide locally on Linux Gentoo (system gcc 6.4.0-r1), numpy fails to load, on firefox (see full log below),

<details>

```
________________________________________________________________ test_import[firefox-numpy] _________________________________________________________________

name = 'numpy', selenium = <test.conftest.FirefoxWrapper object at 0x7f1496993630>

    @pytest.mark.parametrize('name', registered_packages())
    def test_import(name, selenium):
        [...]
>           selenium.run('import %s' % import_name)

test/test_common.py:47: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
test/conftest.py:53: in run
    'return pyodide.runPython({!r})'.format(code))
test/conftest.py:60: in run_js
    return self.driver.execute_script(catch)
../../.miniconda3/envs/pyodide-env/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py:635: in execute_script
    'args': converted_args})['value']
../../.miniconda3/envs/pyodide-env/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py:320: in execute
    self.error_handler.check_response(response)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7f1496993b38>
response = {'status': 500, 'value': '{"value":{"error":"javascript error","message":"Error: Traceback (most recent call last):\\n...1:41937/pyodide.asm.js:4:40671\\n@http://127.0.0.1:41937/test.html:3:26\\n@http://127.0.0.1:41937/test.html:1:2\\n"}}'}

    def check_response(self, response):
        """
        [..]
            raise exception_class(message, screen, stacktrace, alert_text)
>       raise exception_class(message, screen, stacktrace)
E       selenium.common.exceptions.JavascriptException: Message: Error: Traceback (most recent call last):
E         File "/lib/python3.6/site-packages/numpy/core/__init__.py", line 16, in <module>
E           from . import multiarray
E       ImportError: Could not evaluate dynamic lib: /lib/python3.6/site-packages/numpy/core/multiarray.so
E       LinkError: import object field '_cblas_caxpy' is not a Function
E       
E       During handling of the above exception, another exception occurred:
E       
E       Traceback (most recent call last):
E         File "/lib/python3.6/site-packages/pyodide.py", line 33, in eval_code
E           exec(compile(mod, '<exec>', mode='exec'), ns, ns)
E         File "<exec>", line 1, in <module>
E         File "/lib/python3.6/site-packages/numpy/__init__.py", line 142, in <module>
E           from . import add_newdocs
E         File "/lib/python3.6/site-packages/numpy/add_newdocs.py", line 13, in <module>
E           from numpy.lib import add_newdoc
E         File "/lib/python3.6/site-packages/numpy/lib/__init__.py", line 8, in <module>
E           from .type_check import *
E         File "/lib/python3.6/site-packages/numpy/lib/type_check.py", line 11, in <module>
E           import numpy.core.numeric as _nx
E         File "/lib/python3.6/site-packages/numpy/core/__init__.py", line 26, in <module>
E           raise ImportError(msg)
E       ImportError: 
E       Importing the multiarray numpy extension module failed.  Most
E       likely you are trying to import a failed build of numpy.
E       If you're working with a numpy git repo, try `git clean -xdf` (removes all
E       files not under version control).  Otherwise reinstall numpy.
E       
E       Original error was: Could not evaluate dynamic lib: /lib/python3.6/site-packages/numpy/core/multiarray.so
E       LinkError: import object field '_cblas_caxpy' is not a Function

../../.miniconda3/envs/pyodide-env/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py:242: JavascriptException
----------------------------------------------------------------- Captured stdout teardown ------------------------------------------------------------------
Skipping wasm decoding
Python initialization complete
Python exception:
Traceback (most recent call last):
  File "/lib/python3.6/site-packages/numpy/core/__init__.py", line 16, in <module>
    from . import multiarray
ImportError: Could not evaluate dynamic lib: /lib/python3.6/site-packages/numpy/core/multiarray.so
LinkError: import object field '_cblas_caxpy' is not a Function

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/lib/python3.6/site-packages/pyodide.py", line 33, in eval_code
    exec(compile(mod, '<exec>', mode='exec'), ns, ns)
  File "<exec>", line 1, in <module>
  File "/lib/python3.6/site-packages/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/lib/python3.6/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/lib/python3.6/site-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/lib/python3.6/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/lib/python3.6/site-packages/numpy/core/__init__.py", line 26, in <module>
    raise ImportError(msg)
ImportError: 
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: Could not evaluate dynamic lib: /lib/python3.6/site-packages/numpy/core/multiarray.so
LinkError: import object field '_cblas_caxpy' is not a Function


_hiwire_throw_error@http://127.0.0.1:41937/pyodide.asm.js:4:37229
wasm-function[354]@http://127.0.0.1:41937/pyodide_dev.js:813085:1
wasm-function[358]@http://127.0.0.1:41937/pyodide_dev.js:814675:1
pyodide/Module.__runPython@http://127.0.0.1:41937/pyodide.asm.js:4:1877956
_runpython_init_js/Module.runPython@http://127.0.0.1:41937/pyodide.asm.js:4:40671
@http://127.0.0.1:41937/test.html:3:26
@http://127.0.0.1:41937/test.html:1:2
```
</details>

and Chrome,

```
_________________________________________________________________ test_import[chrome-numpy] _________________________________________________________________

name = 'numpy', selenium = <test.conftest.ChromeWrapper object at 0x7f149694c9e8>

    @pytest.mark.parametrize('name', registered_packages())
    def test_import(name, selenium):
[..]
>           selenium.load_package(import_name)

test/test_common.py:46: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
test/conftest.py:67: in load_package
    self.wait.until(PackageLoaded())
[..]
>       raise TimeoutException(message, screen, stacktrace)
E       selenium.common.exceptions.TimeoutException: Message:

../../.miniconda3/envs/pyodide-env/lib/python3.6/site-packages/selenium/webdriver/support/wait.py:80: TimeoutException
----------------------------------------------------------------- Captured stdout teardown ------------------------------------------------------------------
Python initialization complete
Couldn't instantiate wasm: /lib/python3.6/site-packages/numpy/core/multiarray.so 'LinkError: WebAssembly Instantiation: Import #244 module="env" function="_cblas_caxpy" error: function import requires a callable'
Couldn't instantiate wasm: /lib/python3.6/site-packages/numpy/core/umath.so 'ReferenceError: err is not defined'
Couldn't instantiate wasm: /lib/python3.6/site-packages/numpy/core/umath_tests.so 'ReferenceError: err is not defined'
Couldn't instantiate wasm: /lib/python3.6/site-packages/numpy/core/test_rational.so 'ReferenceError: err is not defined'
Couldn't instantiate wasm: /lib/python3.6/site-packages/numpy/core/struct_ufunc_test.so 'ReferenceError: err is not defined'
Couldn't instantiate wasm: /lib/python3.6/site-packages/numpy/core/multiarray_tests.so 'ReferenceError: err is not defined'
Couldn't instantiate wasm: /lib/python3.6/site-packages/numpy/core/operand_flag_tests.so 'ReferenceError: err is not defined'
Couldn't instantiate wasm: /lib/python3.6/site-packages/numpy/fft/fftpack_lite.so 'ReferenceError: err is not defined'
Couldn't instantiate wasm: /lib/python3.6/site-packages/numpy/linalg/lapack_lite.so 'ReferenceError: err is not defined'
Couldn't instantiate wasm: /lib/python3.6/site-packages/numpy/linalg/_umath_linalg.so 'ReferenceError: err is not defined'
Couldn't instantiate wasm: /lib/python3.6/site-packages/numpy/random/mtrand.so 'ReferenceError: err is not defined'
```

Both seemingly due to an issue with `_cblas_caxpy`.  This uses https://github.com/iodide-project/pyodide/pull/98 but it could be reproduced just  by loading and importing numpy.

Not sure what other information might be useful for debugging.

Apart from that, all core cpython tests that pass on Circle CI also pass locally for me.

**Comment by mdboom** [comment]
I suspect the native build of Numpy is finding something on your system that it isn't finding on mine.  I use a clean Conda install of Python which basically nothing in it to build Pyodide.  Are you able to see if that works for you?  If so, maybe we should recommend that in the docs.

Another way to debug that would be if you could post your `build.log` in `packages/numpy/build/numpy-1.14.1/build.log` and we could compare it to mine to see where the difference is.

**Comment by rth** [comment]
I was using a clean Conda virtualenv with just Python, pytest, and nodejs to get the few js dependencies.

Here is my [build.log](https://github.com/iodide-project/pyodide/files/2303791/build.log), I can't see anything suspicious there. Though are includes are scanned left to right? e.g.
```
cc [..] -I/usr/local/include -I/home/rth/src/pyodide/cpython/build/3.6.4/host/include ...
```
if the left include is scanned before the right one, it will get the BLAS headers from my system, that it will not be able to link against later on..

**Comment by mdboom** [comment]
`pywasmcross` automatically removes any includes from `/usr`, so having that there shouldn't matter.

I think what's happening is you have the blas headers installed somewhere on your system.  The native Numpy build is finding them, rather than using its internal blas_lite/lapack_lite.  We just need to find the configuration hook to force using the local copy.  The difference between your `build.log` and mine is that yours contains `-DHAVE_CBLAS=1`.

I think the logic to determine which blas to use is in `numpy/distutils/system_info.py::blas_opt_info`.  I don't see a way to set a config value to influence that, so we'll probably need to add a patch.  I'm going to see if I can reproduce what you're seeing and see if I can make a workaround.
