### ISSUE TITLE
Error building `master` branch on Fedora 32.

### ISSUE THREAD

**Issue by atilag** [iodide-project/pyodide#1272]
Hi team
I'm getting this error while building natively (`make`) on my Fedora 32 box:
```bash
[...]
Installed /home/jgomez/pyodide/packages/.artifacts/lib/python/Pillow-8.0.1-py3.7-linux-x86_64.egg
Processing dependencies for Pillow==8.0.1
Finished processing dependencies for Pillow==8.0.1
src/_imaging.c:75:10: fatal error: 'Python.h' file not found
#include "Python.h"
         ^~~~~~~~~~
1 error generated.
emcc: error: 'ccache /home/jgomez/pyodide/emsdk/emsdk/upstream/bin/clang -DEMSCRIPTEN -fignore-exceptions -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -Xclang -iwithsysroot/include/SDL -I/home/jgomez/pyodide/emsdk/emsdk/upstream/emscripten/cache/sysroot/include/freetype2/freetype -target wasm32-unknown-emscripten -D__EMSCRIPTEN_major__=2 -D__EMSCRIPTEN_minor__=0 -D__EMSCRIPTEN_tiny__=14 -D_LIBCPP_ABI_VERSION=2 -Dunix -D__unix -D__unix__ -flegacy-pass-manager -Werror=implicit-function-declaration --sysroot=/home/jgomez/pyodide/emsdk/emsdk/upstream/emscripten/cache/sysroot -Xclang -iwithsysroot/include/compat -fPIC -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DHAVE_LIBJPEG -DHAVE_LIBZ -DPILLOW_VERSION="8.0.1" -I/home/jgomez/pyodide/packages/pillow/build/Pillow-8.0.1 -I/home/jgomez/anaconda3/include -I/home/jgomez/pyodide/cpython/installs/python-3.8.2/include/python3.7 -c src/_imaging.c -o build/temp.linux-x86_64-3.7/src/_imaging.o' failed (1)
emcc -fPIC -s USE_ZLIB=1 -s USE_LIBJPEG=1 -s USE_FREETYPE=1 -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DHAVE_LIBJPEG -DHAVE_LIBZ -DPILLOW_VERSION="8.0.1" -I/home/jgomez/pyodide/packages/pillow/build/Pillow-8.0.1 -I/home/jgomez/anaconda3/include -I/home/jgomez/pyodide/cpython/installs/python-3.8.2/include/python3.7 -c src/_imaging.c -o build/temp.linux-x86_64-3.7/src/_imaging.o
[...]
```
I'm quite new to the project, but looks like the build env is not finding my Python-devel env?
Thanks!!

**Comment by mgreminger** [comment]
I'm having issues compiling Pillow as well on Ubuntu 20.04, though I'm getting a different error message. 

```
emcc: error: ignoring unsupported linker flag: `-rpath=/home/grem/anaconda3/envs/pyodide-dev/lib` [-Wlinkflags] [-Werror]
emcc -fPIC -s USE_ZLIB=1 -s USE_LIBJPEG=1 -s USE_FREETYPE=1 -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/grem/git/pyodide/packages/pillow/build/Pillow-8.0.1 -I/home/grem/anaconda3/envs/pyodide-dev/include -I/home/grem/git/pyodide/cpython/installs/python-3.8.2/include/python3.8 -c src/_imagingft.c -o build/temp.linux-x86_64-3.8/src/_imagingft.o
emcc -fPIC -s USE_ZLIB=1 -s USE_LIBJPEG=1 -s USE_FREETYPE=1 -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/grem/git/pyodide/packages/pillow/build/Pillow-8.0.1 -I/home/grem/anaconda3/envs/pyodide-dev/include -I/home/grem/git/pyodide/cpython/installs/python-3.8.2/include/python3.8 -c src/_imagingmath.c -o build/temp.linux-x86_64-3.8/src/_imagingmath.o
emcc -fPIC -s USE_ZLIB=1 -s USE_LIBJPEG=1 -s USE_FREETYPE=1 -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DHAVE_LIBJPEG -DHAVE_LIBZ -DPILLOW_VERSION="8.0.1" -I/home/grem/git/pyodide/packages/pillow/build/Pillow-8.0.1 -I/home/grem/anaconda3/envs/pyodide-dev/include -I/home/grem/git/pyodide/cpython/installs/python-3.8.2/include/python3.8 -c src/_imaging.c -o build/temp.linux-x86_64-3.8/src/_imaging.o
emcc -fPIC -s USE_ZLIB=1 -s USE_LIBJPEG=1 -s USE_FREETYPE=1 -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/grem/git/pyodide/packages/pillow/build/Pillow-8.0.1 -I/home/grem/anaconda3/envs/pyodide-dev/include -I/home/grem/git/pyodide/cpython/installs/python-3.8.2/include/python3.8 -c src/_imagingtk.c -o build/temp.linux-x86_64-3.8/src/_imagingtk.o
emcc -O2 -Werror -s EMULATE_FUNCTION_POINTER_CASTS=1 -s BINARYEN_EXTRA_PASSES="--pass-arg=max-func-params@61" -s SIDE_MODULE=1 -s WASM=1 --memory-init-file 0 -s LINKABLE=1 -s EXPORT_ALL=1 -s USE_LIBJPEG=1 -s USE_FREETYPE=1 -ljpeg -L/home/grem/anaconda3/envs/pyodide-dev/lib -Wl,-rpath=/home/grem/anaconda3/envs/pyodide-dev/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.8/src/_imagingft.o -L/home/grem/git/pyodide/packages/pillow/build/Pillow-8.0.1 -L/home/grem/anaconda3/envs/pyodide-dev/lib -o build/lib.linux-x86_64-3.8/PIL/_imagingft.cpython-38-x86_64-linux-gnu.so
```
The issue is the -rpath argument pointing to my conda virtualenv passed to the linker. This is an interaction between conda environments and setuptools, though I'm not sure why it's showing up for Pillow but not other setuptools builds. I even tried building pillow on a clean account using the system python and pip installing all of the build requirements (using the pip command from the Docker config). In that case, the build failed with yet a different error message. I don't have it anymore but it came down to `-m` and `-z` linker flags that are not supported by emscripten.  I think it has to do with how Ubuntu has their Python 3.8.5 configured. I'm not sure what distro the Docker image uses.

I'm not sure why the Pillow package has these issues but it seems to be more sensitive to host Python configuration than the other packages.

**Comment by atilag** [comment]
@mgreminger I'd recommend filling a new issue for you problem :)

**Comment by dalcde** [comment]
What happens when you try to build Pillow outside of pyodide? Try to run

pip3 install --force-reinstall --user --no-binary Pillow Pillow

**Comment by rth** [comment]
@atilag I think the issue is with,

> -I/home/jgomez/pyodide/cpython/installs/python-3.8.2/include/python3.7
> [..]
> -o build/temp.linux-x86_64-3.7/src/_imaging.o

It looks like you are building with Python 3.7 while pyodide requires 3.8

**Comment by rth** [comment]
> The issue is the -rpath argument pointing to my conda virtualenv passed to the linker. This is an interaction between conda environments and setuptools,

Hmm, yes, there was a fix for conda virtualenvs in https://github.com/iodide-project/pyodide/pull/835, but it's possible that additional fixes are necessary since https://github.com/iodide-project/pyodide/pull/1102 . I'll try to reproduce it locally.

**Comment by atilag** [comment]
> It looks like you are building with Python 3.7 while pyodide requires 3.8
Yes, I was using Python 3.7 on my Anaconda3 virtual env, so I exited from the virtual env and tried to install a fresh clone:
```
# Generate sysconfigdata. It outputs into a subfolder of build/, and
# the subfolder is written to pybuilddir.txt.
_PYTHON_SYSCONFIGDATA_NAME=_sysconfigdata__emscripten_ _PYTHON_PROJECT_BASE=/home/jgomez/pyodide/cpython/build/Python-3.8.2 python -m sysconfig --generate-posix-vars
Traceback (most recent call last):
  File "/usr/lib64/python3.8/sysconfig.py", line 371, in _generate_posix_vars
    with open(config_h) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/jgomez/pyodide/cpython/build/Python-3.8.2/pyconfig-64.h'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/lib64/python3.8/sysconfig.py", line 711, in <module>
    _main()
  File "/usr/lib64/python3.8/sysconfig.py", line 699, in _main
    _generate_posix_vars()
  File "/usr/lib64/python3.8/sysconfig.py", line 377, in _generate_posix_vars
    raise OSError(msg)
OSError: invalid Python installation: unable to open /home/jgomez/pyodide/cpython/build/Python-3.8.2/pyconfig-64.h (No such file or directory)
make[1]: *** [Makefile:34: /home/jgomez/pyodide/cpython/installs/python-3.8.2/lib/libpython3.8.a] Error 1
make[1]: Leaving directory '/home/jgomez/pyodide/cpython'
make: *** [Makefile:170: cpython/installs/python-3.8.2/lib/python3.8] Error 2
```

**Comment by atilag** [comment]
Ok, I manage to build it!
I was not running the emsdk.sh script between the first `make`  and the second one.
