### ISSUE TITLE
runPythonAsync causes Python exception: AttributeError: 'method' object has no attribute 'prototype'

### ISSUE THREAD

**Issue by ChristopherHButler** [iodide-project/pyodide#1319]
I have been using pyodide in a project and calling pyodide.runPythonAsync with great success (Great Success!) but recently (the last few days) I am getting a new error: 

```
Python exception:
AttributeError: 'method' object has no attribute 'prototype'

Python exception:
Traceback (most recent call last):
  File "/lib/python3.8/asyncio/tasks.py", line 661, in ensure_future
    task = loop.create_task(coro_or_future)
  File "/lib/python3.8/site-packages/pyodide/webloop.py", line 190, in create_task
    task = tasks.Task(coro, loop=self, name=name)
  File "/lib/python3.8/asyncio/tasks.py", line 164, in __init__
    self._loop.call_soon(self.__step, context=self._context)
  File "/lib/python3.8/site-packages/pyodide/webloop.py", line 99, in call_soon
    return self.call_later(delay, callback, *args, context=context)
  File "/lib/python3.8/site-packages/pyodide/webloop.py", line 139, in call_later
    setTimeout(h._run, delay * 1000)
JsException: PythonError: AttributeError: 'method' object has no attribute 'prototype'
```

Wondering if this is related to the #1310 ?

I am using `https://cdn.jsdelivr.net/pyodide/dev/full/pyodide.js`

**Comment by hoodmane** [comment]
Thanks for the report. Can you provide code that triggers the error?

**Comment by ChristopherHButler** [comment]
Sure thing @hoodmane 

So I am running this in a React app and it was working up until a few days ago. I believe the specific line is: 

```
const result = await pyodide.runPythonAsync(codeToRun, messageCallback, errorCallback);
```

Here is the full function I use to run the python code. Please also feel free to give any pointers if I am not using the library correctly (for example if I should garbage collect `pyodideGlobals`). I also load pyodide from a cdn as mentioned in my previous comment. Let me know if I can help, I'm keen to get this working again

```
/**
 * @desc Runs a string of Python code from Javascript.
 * @param {string} codeToRun python code to run
 * @param {function} messageCallback A callback, called with progress messages. (optional)
 * @param {function} errorCallback A callback, called with error/warning messages. (optional)
 * @returns result of the python code converted to JavaScript
 */
export const runPythonAsync = async ({ codeToRun, messageCallback, errorCallback }) => {
  try {
    if (!pyodide) {
      return {
        globals: null,
        code: null,
        expressions: [],
        logs: [],
        err: {
          message: 'pyodide not detected',
        },
      };
    }

    // load packages
    // await pyodide.loadPackage(['matplotlib']);

    self.runPythonAsyncWrapper = async () => {
      try {
        const result = await pyodide.runPythonAsync(codeToRun, messageCallback, errorCallback);
        const stdout = pyodide.runPython("sys.stdout.getvalue()");

        // want to garbage collect this so put it in seperate variable
        const pyodideGlobals = pyodide.globals.toJs();

        // want to get entries after this one since Map's keep track of order added
        const temp = getEntriesAfterByKey(pyodideGlobals, 'runPythonAsyncWrapper');

        // convert map to object
        const globals = { ...Object.fromEntries(temp) };

        // An additional limitation is that when passing a Python object to Javascript,
        // there is no way for Javascript to automatically garbage collect that object.
        // Therefore, custom Python objects must be manually destroyed when passed to Javascript, or they will leak.
        // To do this, call .destroy() on the object, after which Javascript will no longer have access to the object.
        // pyodideGlobals.destroy();


        // console.log('globals: ', globals);
        // console.log('JSON.stringify(globals): ', JSON.stringify(globals));

        let lines;
        let logs;
        if (stdout) {

          // these are not really expressions like in evaluator
          lines = stdout.split('\n').filter(line => line !== '').map((line, idx) => {
            return {
              line: idx + 1,
              type: 'console',
              rawValue: line,
              strValue: line,
            };
          });

          // format the print statements sent to stdout
          // eslint-disable-next-line no-shadow
          logs = stdout.split('\n').filter(line => line !== '').map(log => {
            return {
              method: CONSOLE_METHODS.LOG.value,
              id: shortid.generate(),
              data: [log],
            };
          });
        }

        return {
          globals,
          code: result,
          expressions: stdout ? lines : [],
          logs: stdout ? logs : [],
          err: null,
        };
      } catch (error) {
        return {
          globals: null,
          code: null,
          expressions: [],
          logs: [],
          err: error,
        };
      }
    };

    self.inputWrapper = (input) => {
      // eslint-disable-next-line no-alert
      return prompt(input);
    };

    // redirect stdout to io.StringIO so that we can get it later
    return pyodide.runPythonAsync(`
      import io, code, sys
      from js import runPythonAsyncWrapper
      from js import inputWrapper
      input = inputWrapper
      __builtins__.input = inputWrapper
      sys.stdout = io.StringIO()
      sys.stderr = io.StringIO()
      ## This runs self.runPythonAsyncWrapper defined in the JS
      runPythonAsyncWrapper()
    `);

  } catch (error) {
    // eslint-disable-next-line no-console
    console.log('error running python code...: ', error);
    return {
      globals: null,
      code: null,
      expressions: [],
      logs: [],
      err: error,
    };
  }
};


/**
 * Filters a Map of entries and returns only entries after a target key.
 * @param {Map} map the map of values you want to check
 * @param {*} targetKey the last entry before the entries you want to return
 * @returns {Map} a filtered map of entries after the target entry.
 */
const getEntriesAfterByKey = (map, targetKey) => {
  const entriesAfter = new Map();
  let seen = false;
  // eslint-disable-next-line no-restricted-syntax
  for (const [key, value] of map.entries()) {
    if (seen) {
      entriesAfter.set(key, value);
    } else if (key === targetKey) {
      seen = true;
    }
  }
  return entriesAfter;
};

```

**Comment by ChristopherHButler** [comment]
Any updates on this @hoodmane ?

**Comment by hoodmane** [comment]
I think `pyodideGlobals` should be a javascript `Map` which javascript can gc automatically when you are done with it. You should definitely NOT destroy `pyodide.globals` itself, `pyodide` will quit working.

You might want to change the `if(!pyodide)` guard to `if(!languagePluginLoader)` and then `await languagePluginLoader` before the body of the function.

You can also avoid the extra copy of globals with:
```js
const entriesAfter = new Map();
let seen = false;
let iter = pyodide.globals.items();
for(let [key, value] of iter){
    if (seen) {
      entriesAfter.set(key, value);
    } else if (key === targetKey) {
      seen = true;
    } else if(value?.destroy) {
        value.destroy();
    }
}
iter.destroy();
```
Also, when you are done with the returned `globals` you should iterate over it and `destroy` all the values. 

For standard out and standard error redirection, I'd suggest 
```py
from contextlib import redirect_stdout, redirect_stderr
my_stdout = io.StringIO()
my_stderr = io.StringIO()
with redirect_stdout(my_stdout), redirect_stderr(my_stderr):
   # do stuff
```

**Comment by hoodmane** [comment]
It's difficult for me to address your main issue based on what you've said, could you give me a complete set of code that actually produces the error? Does it happen for every input to this function? Some particular inputs?

**Comment by hoodmane** [comment]
Running your code in https://pyodide-cdn2.iodide.io/dev/full/console.html, I don't see the error you indicated.

**Comment by ChristopherHButler** [comment]
Sorry for the delayed response. I am still getting the errors even after trying your suggestions (thank you for the code review by the way!) so I need to dig into it a bit more to figure out what's really going on. I'll get back to you if I find something worth sharing with the community.

**Comment by ChristopherHButler** [comment]
Hi again @hoodmane 
I have some updated Error Information:

```
error running python code...:  PythonError: Traceback (most recent call last):
  File "/lib/python3.8/asyncio/tasks.py", line 661, in ensure_future
    task = loop.create_task(coro_or_future)
  File "/lib/python3.8/site-packages/pyodide/webloop.py", line 190, in create_task
    task = tasks.Task(coro, loop=self, name=name)
  File "/lib/python3.8/asyncio/tasks.py", line 164, in __init__
    self._loop.call_soon(self.__step, context=self._context)
  File "/lib/python3.8/site-packages/pyodide/webloop.py", line 99, in call_soon
    return self.call_later(delay, callback, *args, context=context)
  File "/lib/python3.8/site-packages/pyodide/webloop.py", line 139, in call_later
    setTimeout(h._run, delay * 1000)
JsException: PythonError: AttributeError: 'method' object has no attribute 'prototype'


    at new_error (https://cdn.jsdelivr.net/pyodide/dev/full/pyodide.asm.js:9:179863)
    at wrap_exception (https://cdn.jsdelivr.net/pyodide/dev/full/pyodide.asm.wasm:wasm-function[297]:0x1a7acf)
    at pythonexc2js (https://cdn.jsdelivr.net/pyodide/dev/full/pyodide.asm.wasm:wasm-function[298]:0x1a7c1c)
    at Proxy._ensure_future (https://cdn.jsdelivr.net/pyodide/dev/full/pyodide.asm.js:9:187390)
    at Proxy.then (https://cdn.jsdelivr.net/pyodide/dev/full/pyodide.asm.js:9:187565)
```

**Comment by hoodmane** [comment]
Thanks for continuing with this report. It would still really help if you could provide better info on the reproduction. Which browsers have you tested this on? Can you give me a self contained block of code that is triggering the bug? It would be particularly helpful to have a block of javascript that triggers the problem when pasted into the browser console in `https://pyodide-cdn2.iodide.io/dev/full/console.html`.
Without the ability to reproduce the issue it's really hard to understand what's going on.

**Comment by ChristopherHButler** [comment]
Hey again,

I made a super simple app with parts of my actual app cut out so you can take a look. 
Repo: [https://github.com/ChristopherHButler/pyo](https://github.com/ChristopherHButler/pyo)

I am working from a Macbook Pro and only tested on Chrome.

**Comment by ChristopherHButler** [comment]
This seems to be working again with the latest release. I didn't do anything different with my code so no idea why but this issue can probably be closed (although it may come up again...)
