### ISSUE TITLE
"import numpy" runs out of memory on Chrome

### ISSUE THREAD

**Issue by mdboom** [iodide-project/pyodide#17]
```
"Error: Traceback (most recent call last): File "<string>", line 1, in <module> File "/lib/python3.6/site-packages/lazy_import.py", line 124, in __getattribute__ _load_module(self) File "/lib/python3.6/site-packages/lazy_import.py", line 493, in _load_module msg.format(**modclass._lazy_import_error_strings)) from None ImportError: sitecustomize attempted to use a functionality that requires module numpy, but it couldn't be loaded. Please install numpy and retry. at emval_allocator_1 (eval at craftEmvalAllocator (http://127.0.0.1:8000/pyodide.asm.js:1:2949151), <anonymous>:7:11) at __emval_new (http://127.0.0.1:8000/pyodide.asm.js:1:2949581) at RG (http://127.0.0.1:8000/pyodide.asm.js:19:22381) at VG (http://127.0.0.1:8000/pyodide.asm.js:19:27159) at Array.asm.__Z9runPythonNSt3__212basic_stringIwNS_11char_traitsIwEENS_9allocatorIwEEEE (http://127.0.0.1:8000/pyodide.asm.js:36:618068) at ftCall_vii (http://127.0.0.1:8000/pyodide.asm.js:1:3993583) at odc (http://127.0.0.1:8000/pyodide.asm.js:10:141771) at $F (http://127.0.0.1:8000/pyodide.asm.js:19:1710) at asm.__ZN10emscripten8internal7InvokerINS_3valEJNSt3__212basic_stringIwNS3_11char_traitsIwEENS3_9allocatorIwEEEEEE6invokeEPFS2_S9_EPNS0_11BindingTypeIS9_EUt_E (http://127.0.0.1:8000/pyodide.asm.js:36:705906) at Object.runPython (eval at new_ (http://127.0.0.1:8000/pyodide.asm.js:1:2931430), <anonymous>:8:10)"
```

**Comment by mdboom** [comment]
Closing as obsolete: We've since moved to pure WASM from asm.js, which has its own set of issues with Chrome.
