### ISSUE TITLE
numpy.fft doesn't compile when WASM=1

### ISSUE THREAD

**Issue by mdboom** [iodide-project/pyodide#21]
All other modules are working except this one.  Since it's kind of a corner use case for the kinds of data science I anticipate, I'm punting on this for now.  But it would be nice to resolve eventually.

**Comment by mdboom** [comment]
```
invalid call target: invalid call target: $_malloc
invalid call target: $_malloc
invalid call target: Traceback (most recent call last):
  File "/home/mdboom/Work/builds/compiling/pyodide/emsdk/emsdk/emscripten/incoming/emcc", line 10, in <module>
    python_selector.run(__file__, profile=True)
  File "/home/mdboom/Work/builds/compiling/pyodide/emsdk/emsdk/emscripten/incoming/tools/python_selector.py", line 38, in run
    sys.exit(run_by_import(filename, main) if on_allowed_version() else run_by_subprocess(filename))
  File "/home/mdboom/Work/builds/compiling/pyodide/emsdk/emsdk/emscripten/incoming/tools/python_selector.py", line 13, in run_by_import
    return getattr(importlib.import_module(os.path.basename(filename)), main)()
  File "/home/mdboom/Work/builds/compiling/pyodide/emsdk/emsdk/emscripten/incoming/emcc.py", line 1902, in run
    wasm_text_target, misc_temp_files, optimizer)
  File "/home/mdboom/Work/builds/compiling/pyodide/emsdk/emsdk/emscripten/incoming/emcc.py", line 2373, in do_binaryen
    subprocess.check_call(cmd)
  File "/home/mdboom/miniconda3/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
```
