### ISSUE TITLE
first 'make' fail with: Bad file descriptor: '/src/emsdk/emsdk/clang/tag-e1.38.12/build_tag-e1.38.12_64/bin/llvm-nm'

### ISSUE THREAD

**Issue by orengriffin** [iodide-project/pyodide#269]
cloned the repo, ran ./run_docker in and in the container wrote 'make'. 
this ran for ages. more then 6 hours and failed with:
INFO:root: - ok
WARNING:root:retrieving port: freetype from https://github.com/emscripten-ports/FreeType/archive/version_1.zip
WARNING:root:unpacking port: freetype
INFO:root:generating port: freetype.bc... (this will be cached in "/src/emsdk/emsdk/.emscripten_cache/asmjs/freetype.bc" for subsequent builds)
INFO:root: - ok
INFO:root:generating system library: libcxx_noexcept.a... (this will be cached in "/src/emsdk/emsdk/.emscripten_cache/asmjs/libcxx_noexcept.a" for subsequent builds)
INFO:root: - ok
INFO:root:generating system library: libcxxabi.bc... (this will be cached in "/src/emsdk/emsdk/.emscripten_cache/asmjs/libcxxabi.bc" for subsequent builds)
INFO:root: - ok
INFO:root:generating system library: wasm-libc.bc... (this will be cached in "/src/emsdk/emsdk/.emscripten_cache/asmjs/wasm-libc.bc" for subsequent builds)
INFO:root: - ok
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/src/emsdk/emsdk/emscripten/tag-1.38.12/tools/shared.py", line 1419, in g_llvm_nm_uncached
    return Building.llvm_nm_uncached(filename)
  File "/src/emsdk/emsdk/emscripten/tag-1.38.12/tools/shared.py", line 2215, in llvm_nm_uncached
    proc = run_process([LLVM_NM, filename], stdout=stdout, stderr=stderr, check=False)
  File "/src/emsdk/emsdk/emscripten/tag-1.38.12/tools/shared.py", line 158, in run_process
    return run_base(cmd, universal_newlines=universal_newlines, check=check, *args, **kw)
  File "/src/emsdk/emsdk/emscripten/tag-1.38.12/tools/shared.py", line 144, in run_base
    return subprocess.run(cmd, check=check, input=input, *args, **kw)
  File "/usr/local/lib/python3.7/subprocess.py", line 453, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/lib/python3.7/subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.7/subprocess.py", line 1499, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 9] Bad file descriptor: '/src/emsdk/emsdk/clang/tag-e1.38.12/build_tag-e1.38.12_64/bin/llvm-nm'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/src/emsdk/emsdk/emscripten/tag-1.38.12/emcc.py", line 3062, in <module>
    sys.exit(run())
  File "/src/emsdk/emsdk/emscripten/tag-1.38.12/emcc.py", line 1673, in run
    final = shared.Building.link(linker_inputs, DEFAULT_FINAL, force_archive_contents=force_archive_contents, temp_files=misc_temp_files, just_calculate=just_calculate)
  File "/src/emsdk/emsdk/emscripten/tag-1.38.12/tools/shared.py", line 2019, in link
    Building.read_link_inputs([x for x in files if not x.startswith('-')])
  File "/src/emsdk/emsdk/emscripten/tag-1.38.12/tools/shared.py", line 1881, in read_link_inputs
    Building.parallel_llvm_nm(object_names)
  File "/src/emsdk/emsdk/emscripten/tag-1.38.12/tools/shared.py", line 1835, in parallel_llvm_nm
    object_contents = pool.map(g_llvm_nm_uncached, files)
  File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
OSError: [Errno 9] Bad file descriptor: '/src/emsdk/emsdk/clang/tag-e1.38.12/build_tag-e1.38.12_64/bin/llvm-nm'
Makefile:68: recipe for target 'build/pyodide.asm.js' failed
make: *** [build/pyodide.asm.js] Error 1

**Comment by rth** [comment]
Closing as outdated, sorry this never recieved a response in 2018. pyodide now uses esmdk 1.38.30.
