### ISSUE TITLE
Cannot Build on Windows

### ISSUE THREAD

**Issue by tbergeltffs** [iodide-project/pyodide#317]
I am trying to build pyodide-0.7.0 on Windows 10 using the docker container and I am getting errors building scipy. I have tried building using Windows Docker through powershell and using Windows Docker through WSL running Ubuntu with the exact same results. When I do the same build on my MacBook I don't run into any issues building in the docker container.

Here is the relevant logs for the error:
emcc -I../../../../CLAPACK/CLAPACK-WA/INCLUDE -Wno-implicit-function-declaration -Wall -g -ffixed-form -fno-second-underscore -fPIC -O3 -funroll-loops -I/src/cpython/build/3.7.0/host/lib/python3.7/site-packages/numpy-1.15.1-py3.7-linux-x86_64.egg/numpy/core/include -c -c scipy/fftpack/src/dfftpack/zfftb.c -o build/temp.linux-x86_64-3.7/scipy/fftpack/src/dfftpack/zfftb.bc
clang-6.0: warning: argument unused during compilation: '-ffixed-form' [-Wunused-command-line-argument]
clang-6.0: warning: argument unused during compilation: '-fno-second-underscore' [-Wunused-command-line-argument]
Traceback (most recent call last):
  File "/src/cpython/build/3.7.0/host/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/src/cpython/build/3.7.0/host/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/src/pyodide_build/__main__.py", line 30, in <module>
    main()
  File "/src/pyodide_build/__main__.py", line 24, in main
    args.func(args)
  File "/src/pyodide_build/pywasmcross.py", line 396, in main
    build_wrap(args)
  File "/src/pyodide_build/pywasmcross.py", line 363, in build_wrap
    replay_compile(args)
  File "/src/pyodide_build/pywasmcross.py", line 327, in replay_compile
    line = json.loads(line)
  File "/src/cpython/build/3.7.0/host/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/src/cpython/build/3.7.0/host/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/src/cpython/build/3.7.0/host/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 156 (char 155)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/src/pyodide_build/__main__.py", line 30, in <module>
    main()
  File "/src/pyodide_build/__main__.py", line 24, in main
    args.func(args)
  File "/src/pyodide_build/buildall.py", line 93, in main
    build_packages(packagesdir, outputdir, args)
  File "/src/pyodide_build/buildall.py", line 50, in build_packages
    build_package(pkgname, dependencies, packagesdir, outputdir, args)
  File "/src/pyodide_build/buildall.py", line 21, in build_package
    build_package(req, dependencies, packagesdir, outputdir, args)
  File "/src/pyodide_build/buildall.py", line 24, in build_package
    buildpkg.build_package(packagesdir / pkgname / 'meta.yaml', args)
  File "/src/pyodide_build/buildpkg.py", line 162, in build_package
    compile(path, srcpath, pkg, args)
  File "/src/pyodide_build/buildpkg.py", line 100, in compile
    '--target', args.target], env=env, check=True)
  File "/usr/local/lib/python3.7/subprocess.py", line 468, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/src/cpython/build/3.7.0/host/bin/python3', '-m', 'pyodide_build', 'pywasmcross', '--cflags', ' -I../../../../CLAPACK/CLAPACK-WA/INCLUDE -Wno-implicit-function-declaration', '--ldflags', '-O3 -s BINARYEN_METHOD=native-wasm -Werror -s EMULATED_FUNCTION_POINTERS=1 -s EMULATE_FUNCTION_POINTER_CASTS=1 -s SIDE_MODULE=1 -s WASM=1 -s BINARYEN_TRAP_MODE=clamp --memory-init-file 0 -s LINKABLE=1 -s EXPORT_ALL=1 ', '--host', '/src/cpython/build/3.7.0/host', '--target', '/src/cpython/installs/python-3.7.0']' returned non-zero exit status 1.
Makefile:5: recipe for target 'all' failed
make[1]: *** [all] Error 1
make[1]: Leaving directory '/src/packages'
Makefile:215: recipe for target 'build/packages.json' failed
make: *** [build/packages.json] Error 2

And here is the full log from make:
[log.txt](https://github.com/iodide-project/pyodide/files/2846355/log.txt)

**Comment by mdboom** [comment]
Hmm...  This is a puzzler.  I don't know if we have any other developers on Windows.  I would start by searching around for any other common issues in Docker on Windows that might seem relevant here.  My guess is perhaps filesystem differences, since that's one of the few variables one would expect to run into.  As a workaround (and to confirm that theory), you could copy the `src/` directory inside the Docker container to another location and build from there.

**Comment by rth** [comment]
There have been reports that the latest version of pyodide builds fine with WSL2 https://github.com/iodide-project/pyodide/pull/965. So the solution is likely to update from WSL to WSL2 on Windows. Closing as resolved.
