### ISSUE TITLE
Docker make fails with subprocess.CalledProcessError

### ISSUE THREAD

**Issue by scalemailted** [iodide-project/pyodide#395]
I'm using Docker and the `run_docker` script for initial setup. Once complete, I invoke `make` to build. The `make` process took several hours, and finally resulted in the following error message. _Note: I've abridged the console logs._ Additional details: **macOS: Mojave 10.14.1**, Docker: **18.09.2, build 6247962**

> pyodide$  ./run_docker
> ...
> root@199364163f6b:/src# make
> ...
> running install_scripts
> Installing isympy script to install/bin
> Remember to build the main file with  -s FORCE_FILESYSTEM=1  so that it includes support for loading this file package
> converting to ArrayBuffer
> compressing package of size 26270809
> compressed package into 12145241
> compressed in 745 ms
> WARN: Output exceeds 32000 characters
> WARN: Output exceeds 32000 characters
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/src/pyodide_build/__main__.py", line 32, in <module>
>     main()
>   File "/src/pyodide_build/__main__.py", line 26, in main
>     args.func(args)
>   File "/src/pyodide_build/buildall.py", line 91, in main
>     build_packages(packagesdir, outputdir, args)
>   File "/src/pyodide_build/buildall.py", line 48, in build_packages
>     build_package(pkgname, dependencies, packagesdir, outputdir, args)
>   File "/src/pyodide_build/buildall.py", line 22, in build_package
>     buildpkg.build_package(packagesdir / pkgname / 'meta.yaml', args)
>   File "/src/pyodide_build/buildpkg.py", line 189, in build_package
>     srcpath = download_and_extract(buildpath, packagedir, pkg, args)
>   File "/src/pyodide_build/buildpkg.py", line 48, in download_and_extract
>     ], check=True)
>   File "/usr/local/lib/python3.7/subprocess.py", line 468, in run
>     output=stdout, stderr=stderr)
> subprocess.CalledProcessError: Command '['wget', '-q', '-O', '/src/packages/bleach/build/bleach-3.1.0.tar.gz', 'https://files.pythonhosted.org/packages/78/5a/0df03e8735cd9c75167528299c738702437589b9c71a849489d00ffa82e8/bleach-3.1.0.tar.gz']' returned non-zero exit status 4.
> Makefile:5: recipe for target 'all' failed
> make[1]: *** [all] Error 1
> make[1]: Leaving directory '/src/packages'
> Makefile:211: recipe for target 'build/packages.json' failed
> make: *** [build/packages.json] Error 2

**Comment by scalemailted** [comment]
<img width="554" alt="Screenshot 2019-04-23 19 37 34" src="https://user-images.githubusercontent.com/632395/56624633-4928fe80-65ff-11e9-9cc5-b584f3167531.png">

**Comment by scalemailted** [comment]
So I tried typing the command manually that threw the error:
`wget -q -O /src/packages/bleach/build/bleach-3.1.0.tar.gz https://files.pythonhosted.org/packages/78/5a/0df03e8735cd9c75167528299c738702437589b9c71a849489d00ffa82e8/bleach-3.1.0.tar.gz`

and it executed without issue.

So I attempted to invoke `make` again, to repeat the issue, but the install finished properly. Everything is now working

**Comment by scalemailted** [comment]
<img width="453" alt="Screenshot 2019-04-23 21 54 55" src="https://user-images.githubusercontent.com/632395/56629273-7501af80-6612-11e9-947f-4303db87fc17.png">
