### ISSUE TITLE
Micropip Usage

### ISSUE THREAD

**Issue by SimonBiggs** [iodide-project/pyodide#411]
Hi @mdboom :),

I have dived in and attempted to get `micropip` working. To begin testing it out I aimed to use the pure python module `pydicom` which has no dependencies (https://github.com/pydicom/pydicom/blob/master/setup.py#L57).

I wanted to be able to use your latest pyodide release (0.12.0), so I set up the package hosted on netlify:

https://github.com/pymedphys/netlify-pyodide
https://pyodide.pymedphys.com/pyodide.js

I then made the following changes to our documentation website:

https://github.com/pymedphys/pymedphys/pull/252/files

With the key portion being the following:

```javascript
pythonCode = `
import micropip

def something_awesome():
    import pydicom
    print(pydicom)


micropip.install('pydicom').then(something_awesome())
`

languagePluginLoader.then(() => {
    return pyodide.loadPackage(['micropip'])
}).then(() => {
    console.log(pyodide.runPython(pythonCode));
})
```

The live running preview of the docs for this pull request are available at https://deploy-preview-252--pymedphys.netlify.com/

When I go to that site, using Chrome on Ubuntu I am greeted with the following:

![image](https://user-images.githubusercontent.com/6559099/57190995-1a4a4b00-6f64-11e9-852a-b8a0760b9e68.png)

```
pyodide.pymedphys.com/pyodide.asm.js:8 Python initialization complete
pyodide.js:136 Loading micropip from default channel
pyodide.js:136 Loading distlib from default channel
pyodide.asm.js:8 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
_hiwire_call_member @ pyodide.asm.js:8
pyodide.pymedphys.com/pyodide.asm.js:8 Python exception:
pyodide.pymedphys.com/pyodide.asm.js:8 Traceback (most recent call last):
pyodide.pymedphys.com/pyodide.asm.js:8   File "/lib/python3.7/site-packages/pyodide.py", line 44, in eval_code
pyodide.pymedphys.com/pyodide.asm.js:8     return eval(compile(expr, '<eval>', mode='eval'), ns, ns)
pyodide.pymedphys.com/pyodide.asm.js:8   File "<eval>", line 9, in <module>
pyodide.pymedphys.com/pyodide.asm.js:8   File "<exec>", line 5, in something_awesome
pyodide.pymedphys.com/pyodide.asm.js:8 ModuleNotFoundError: No module named 'pydicom'
pyodide.pymedphys.com/pyodide.asm.js:8 
pyodide.pymedphys.com/pyodide.asm.js:8 Uncaught (in promise) Error: Traceback (most recent call last):
  File "/lib/python3.7/site-packages/pyodide.py", line 44, in eval_code
    return eval(compile(expr, '<eval>', mode='eval'), ns, ns)
  File "<eval>", line 9, in <module>
  File "<exec>", line 5, in something_awesome
ModuleNotFoundError: No module named 'pydicom'

    at _hiwire_throw_error (pyodide.pymedphys.com/pyodide.asm.js:8)
    at /wasm-function[356]:1239
    at /wasm-function[383]:265
    at Object.Module.__runPython (pyodide.pymedphys.com/pyodide.asm.js:8)
    at Object.Module._runPythonInternal (pyodide.pymedphys.com/pyodide.asm.js:8)
    at Object.Module.runPython (pyodide.pymedphys.com/pyodide.asm.js:8)
    at theme.js:1
```

At this current point I am a little stumped. Any recommendations on where to go from here?

Thanks @mdboom !! :)

Cheers,
Simon

**Comment by SimonBiggs** [comment]
So, I found my issue... I don't understand why it is an issue, but I found it.

```python
def do_work(*args):
    import snowballstemmer
    stemmer = snowballstemmer.stemmer('english')
    print(stemmer.stemWords('go goes going gone'.split()))

import micropip
micropip.install('snowballstemmer').then(do_work)  # Works
```


```python
def do_work(*args):
    import snowballstemmer
    stemmer = snowballstemmer.stemmer('english')
    print(stemmer.stemWords('go goes going gone'.split()))

import micropip
micropip.install('snowballstemmer').then(do_work())  # Does not work
```

**Comment by SimonBiggs** [comment]
I understand why now :). My original version, the result of the function is being passed to `then()`, which means the function is being run before the promise resolves. However, the second method, only the function itself is passed to `then()`, allowing `then()` to control the execution. Makes sense. Silly me.
