### ISSUE TITLE
open_url does not exist

### ISSUE THREAD

**Issue by PythonLinks** [iodide-project/pyodide#430]

**Comment by PythonLinks** [comment]
On the current produxtion server. 

from js import pyodide

pyodide.open_url

gives the following error
Error: Traceback (most recent call last):
  File "/lib/python3.7/site-packages/pyodide.py", line 44, in eval_code
    return eval(compile(expr, '<eval>', mode='eval'), ns, ns)
  File "<eval>", line 1, in <module>
AttributeError: open_url

_hiwire_throw_error()@https://alpha.iodide.app/pyodide-0.12.0/pyodide.asm.js:8:38602
{anonymous}()@wasm-function[356]:1239
{anonymous}()@wasm-function[383]:265
Object.Module.__runPython()@https://alpha.iodide.app/pyodide-0.12.0/pyodide.asm.js:8:2027156
Object.Module._runPythonInternal()@https://alpha.iodide.app/pyodide-0.12.0/pyodide.asm.js:8:42817
internal()@https://alpha.iodide.app/pyodide-0.12.0/pyodide.asm.js:8:43382
Object.Module.runPythonAsync()@https://alpha.iodide.app/pyodide-0.12.0/pyodide.asm.js:8:43857

py
