### ISSUE TITLE
Docker not building

### ISSUE THREAD

**Issue by drewbitt** [iodide-project/pyodide#440]
On two different systems, the `./run_docker` and then `make` is not working. Error on `make -C emsdk`
```
Fetching all tags from Emscripten Github repository...
Done. 160 tagged releases available, latest is 1.38.32.
Fetching all tags from Binaryen Github repository...
Done. 87 tagged Binaryen releases available, latest is 1.38.32.
Fetching all precompiled tagged releases..
Downloading: /src/emsdk/emsdk/llvm-tags-32bit.txt from https://s3.amazonaws.com/mozilla-games/emscripten/packages/llvm/tag/linux_32bit/index.txt
Downloading: /src/emsdk/emsdk/llvm-tags-64bit.txt from https://s3.amazonaws.com/mozilla-games/emscripten/packages/llvm/tag/linux_64bit/index.txt, 2379 Bytes
Downloading: /src/emsdk/emsdk/upstream/lkgr.json from https://storage.googleapis.com/wasm-llvm/builds/linux/lkgr.json, 3690 Bytes
Traceback (most recent call last):
  File "./emsdk", line 2605, in <module>
    sys.exit(main())
  File "./emsdk", line 2369, in main
    load_sdk_manifest()
  File "./emsdk", line 1977, in load_sdk_manifest
    elif '%releases-tag%' in t.version: expand_category_param('%releases-tag%', releases_tags, t, is_sdk=False)
  File "./emsdk", line 1933, in expand_category_param
    ver = category_list[i]
TypeError: 'dict_values' object does not support indexing
Makefile:10: recipe for target 'emsdk/.complete' failed
make[1]: *** [emsdk/.complete] Error 1
make[1]: Leaving directory '/src/emsdk'
Makefile:214: recipe for target 'emsdk/emsdk/.complete' failed
make: *** [emsdk/emsdk/.complete] Error 2
```

**Comment by drewbitt** [comment]
Seems to have been a download of emsdk issue. It now works on both hours later.
