### ISSUE TITLE
Matplotlib web assembly backend causes failures in webworker

### ISSUE THREAD

**Issue by SimonBiggs** [iodide-project/pyodide#442]
Matplotlib tries to run `from js import document`. This causes an exception when Pyodide is being run from within a webworker.

**Comment by mdboom** [comment]
The wasm backend wouldn't work in a webworker because it requires the DOM.  However, running data-only backends in matplotlib seems useful and desirable.

Is this also true if you do

```
import matplotlib
matplotlib.use('Agg')
```

?

**Comment by SimonBiggs** [comment]
Unfortunately I couldn't actually test that as when I tried to change the backend I ran into https://github.com/iodide-project/pyodide/issues/441

That issue certainly was not matplotlib specific. I initially bumped into it running my own code, but I chose matplotlib just as an example that removes as much extra complications out of it...

**Comment by worrel** [comment]
I also recently encountered this problem and `matplotlib.use()` (as suggested in https://github.com/iodide-project/pyodide/issues/442#issuecomment-498784449) doesn't work because the backend has to be set before the `matplotlib` import.

The following approach -overriding the `MPLBACKEND` env var right up front- appears to work:

```python
import os
os.environ['MPLBACKEND'] = 'AGG'

# keep calm & carry on as usual e.g.:
import matplotlib as mpl
```

**Comment by Sachin5411** [comment]
> I also recently encountered this problem and `matplotlib.use()` (as suggested in [#442 (comment)](https://github.com/iodide-project/pyodide/issues/442#issuecomment-498784449)) doesn't work because the backend has to be set before the `matplotlib` import.
> 
> The following approach -overriding the `MPLBACKEND` env var right up front- appears to work:
> 
> ```python
> import os
> os.environ['MPLBACKEND'] = 'AGG'
> 
> # keep calm & carry on as usual e.g.:
> import matplotlib as mpl
> ```

facing the same issue, import matplotlib is working fine...
but as soon as i call matplotlib.pyplot , it shows the following error`Error: Traceback (most recent call last):
  File "/lib/python3.7/site-packages/pyodide.py", line 43, in eval_code
    exec(compile(mod, '<exec>', mode='exec'), ns, ns)
  File "<exec>", line 4, in <module>
  File "/lib/python3.7/site-packages/matplotlib/pyplot.py", line 115, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/lib/python3.7/site-packages/matplotlib/backends/__init__.py", line 62, in pylab_setup
    [backend_name], 0)
  File "/lib/python3.7/site-packages/matplotlib/backends/wasm_backend.py", line 23, in <module>
    from js import document
ImportError: cannot import name 'document' from 'js' (unknown location)`

Any help would be appreciated !!.. Thanx in advance
