### ISSUE TITLE
micropip source removed on make clean

### ISSUE THREAD

**Issue by rth** [iodide-project/pyodide#467]
Currently, the `micropip` source is stored under `packages/micropip/build/micropip-0.1/`. The issue is that if one runs `make clean`, all build subfolder in `packages` are removed, including this folder. This leads to the following error,
```py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/src/pyodide_build/__main__.py", line 32, in <module>
    main()
  File "/src/pyodide_build/__main__.py", line 26, in main
    args.func(args)
  File "/src/pyodide_build/buildall.py", line 92, in main
    build_packages(packagesdir, outputdir, args)
  File "/src/pyodide_build/buildall.py", line 49, in build_packages
    build_package(pkgname, dependencies, packagesdir, outputdir, args)
  File "/src/pyodide_build/buildall.py", line 23, in build_package
    buildpkg.build_package(packagesdir / pkgname / 'meta.yaml', args)
  File "/src/pyodide_build/buildpkg.py", line 194, in build_package
    patch(path, srcpath, pkg, args)
  File "/src/pyodide_build/buildpkg.py", line 69, in patch
    os.chdir(srcpath)
FileNotFoundError: [Errno 2] No such file or directory: '/src/packages/micropip/build/micropip-0.1'
```

It would probably be better to store the source of micropip elsewhere (to avoid adding exceptions to `make clean`).

**Comment by phorward** [comment]
Hi there, 37f0855eaaecdebfe3b632d39838202d55a499ee from #324 solves this using the local packages source feature.
