### ISSUE TITLE
Uncaught (in promise) Error: No exception type or value 

### ISSUE THREAD

**Issue by leopsidom** [iodide-project/pyodide#630]
I am trying to use the `pyodide.autocomplete` feature by simply invoking `pyodide.autocomplete('de')` but got above error. Did I use it in a wrong way ? Here is where the error happens:

```
  Module.autocomplete =
      function(path) {
    var pyodide_module = Module.pyimport("pyodide");    <<<<<< this line
    return pyodide_module.get_completions(path);
  }
```

Here is the stack trace:

> pyodide.asm.js:8 Uncaught (in promise) Error: No exception type or value
    at _hiwire_throw_error (https://pyodide.cdn.iodide.io/pyodide.asm.js:8:38727)
    at wasm-function[358]:0xfc6c0
    at wasm-function[347]:0xfb9ad
    at Object.Module.__pyimport (https://pyodide.cdn.iodide.io/pyodide.asm.js:8:2027635)
    at Object.Module.pyimport (https://pyodide.cdn.iodide.io/pyodide.asm.js:8:39488)
    at Object.Module.autocomplete (https://pyodide.cdn.iodide.io/pyodide.js:330:33)
    at http://localhost:8080/webworker.js:48:40

Thanks

**Comment by rth** [comment]
We have deprecated the autocomplete API https://github.com/iodide-project/pyodide/pull/1066 in favor of using jedi directly. Closing.  Don't hesitate to open other issues if you encounter any.
