### ISSUE TITLE
ModuleNotFoundError: No module named 'numpy'

### ISSUE THREAD

**Issue by gbtami** [iodide-project/pyodide#66]
I wanted to try https://iodide.io/pyodide-demo/python.html
Clicked on "Run All Cells"
Everything seems OK until the cell `import numpy as `np`

```
Error: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'numpy'

_hiwire_throw_error@https://iodide.io/pyodide-demo/pyodide.asm.js:4:36646
wasm-function[346]@https://iodide.io/dist/iodide.pyodide-20180605.js line 12 > eval:774898:1
wasm-function[350]@https://iodide.io/dist/iodide.pyodide-20180605.js line 12 > eval:776709:1
pyodide/Module.__runPython@https://iodide.io/pyodide-demo/pyodide.asm.js:4:1860011
_runpython_init/Module.runPython@https://iodide.io/pyodide-demo/pyodide.asm.js:4:40006
C/</p</<@https://iodide.io/dist/iodide.pyodide-20180605.js:12:191453
r/</</<@https://iodide.io/dist/iodide.pyodide-20180605.js:110:12423
dispatch@https://iodide.io/dist/iodide.pyodide-20180605.js:46:27803
C/</p<@https://iodide.io/dist/iodide.pyodide-20180605.js:12:191240
```

Tested on XUbuntu 18.04 Firefox 60.0.2 64bit in New Private Window.

**Comment by mdboom** [comment]
Thanks for the report.

This should have been fixed in #58, which was just merged yesterday, and didn't deploy until just now.  Can you clear your browser cache, try again, and report back?

**Comment by gbtami** [comment]
It's OK now, thx!

**Comment by vadimkantorov** [comment]
Hitting this issue:

```
%% fetch
arrayBuffer: zipball=https://cors-anywhere.herokuapp.com/https://github.com/vadimkantorov/test/archive/master.zip
%% py
import os, sys, io, shutil, zipfile, js

if not os.path.exists('test'):
    with zipfile.ZipFile(io.BytesIO(js.zipball)) as zf:
        zf.extractall('.')
    shutil.move('test-master', 'test')
    sys.path.append('.')
%% py
import test
import test.a

#   File "/lib/python3.7/site-packages/pyodide.py", line 42, in eval_code
#    exec(compile(mod, '<exec>', mode='exec'), ns, ns)
#  File "<exec>", line 2, in <module>
#  File "./test/a.py", line 1, in <module>
#    import numpy as np
#ModuleNotFoundError: No module named 'numpy'
```

```
# a.py
import numpy as np
```

It works if instead I do:
```
import numpy as np
import test
import test.a
```

@mdboom

**Comment by mdboom** [comment]
This is working as expected.  If pyodide doesn't know that your test module depends on Numpy, you would have to explicitly import it from the top-level code, or call `pyodide.loadPackage` from the Javascript side.  We considered, but ultimately rejected, downloading missing modules when they are imported from anywhere.  This is problematic because (a) it must be done asynchronously and Python's `import` is a synchronous API and (b) this could make the wrong choice due to namespace collisions.
