### ISSUE TITLE
fseeko/ftello: implicit declaration is invalid in C99 [-Werror,-Wimplicit-function-declaration]

### ISSUE THREAD

**Issue by Hiisi5** [iodide-project/pyodide#682]
Hello.
I'm trying to build [MDAnalysis](https://www.mdanalysis.org/) as pyodide module. Here's what I'm trying yo do.
Step 1. I'm using docker image. First, I have created the package yaml file by running:
```
bin/pyodide mkpkg MDAnalysis
```
Step 2. Running make in /src dir:
```
MDAnalysis/lib/formats/src/xdrfile.c:2611:12: error: implicit declaration of function 'ftello' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    return ftello((FILE *) xdrs->x_private);
           ^
MDAnalysis/lib/formats/src/xdrfile.c:2611:12: note: did you mean 'ftell'?
/src/emsdk/emsdk/emscripten/tag-1.38.30/system/include/libc/stdio.h:76:6: note: 'ftell' declared here
long ftell(FILE *);
     ^
MDAnalysis/lib/formats/src/xdrfile.c:2627:9: error: implicit declaration of function 'fseeko' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        return fseeko((FILE *) xdrs->x_private, pos, whence) < 0 ? errno : exdrOK;
               ^
MDAnalysis/lib/formats/src/xdrfile.c:2627:9: note: did you mean 'fseek'?
/src/emsdk/emsdk/emscripten/tag-1.38.30/system/include/libc/stdio.h:75:5: note: 'fseek' declared here
int fseek(FILE *, long, int);
    ^
21 warnings and 2 errors generated.
shared:ERROR: compiler frontend failed to generate LLVM bitcode, halting
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/src/pyodide_build/__main__.py", line 32, in <module>
    main()
  File "/src/pyodide_build/__main__.py", line 26, in main
    args.func(args)
  File "/src/pyodide_build/buildall.py", line 91, in main
    build_packages(packagesdir, outputdir, args)
  File "/src/pyodide_build/buildall.py", line 48, in build_packages
    build_package(pkgname, dependencies, packagesdir, outputdir, args)
  File "/src/pyodide_build/buildall.py", line 22, in build_package
    buildpkg.build_package(packagesdir / pkgname / 'meta.yaml', args)
  File "/src/pyodide_build/buildpkg.py", line 210, in build_package
    compile(path, srcpath, pkg, args)
  File "/src/pyodide_build/buildpkg.py", line 122, in compile
    '--target', args.target], env=env, check=True)
  File "/usr/local/lib/python3.7/subprocess.py", line 468, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/src/cpython/build/3.7.0/host/bin/python3', '-m', 'pyodide_build', 'pywasmcross', '--cflags', ' ', '--ldflags', '-O3 -std=c11 -D_FILE_OFFSET_BITS=64 -s BINARYEN_METHOD=native-wasm -Werror -s EMULATED_FUNCTION_POINTERS=1 -s EMULATE_FUNCTION_POINTER_CASTS=1 -s SIDE_MODULE=1 -s WASM=1 -s BINARYEN_TRAP_MODE=clamp --memory-init-file 0 -s LINKABLE=1 -s EXPORT_ALL=1 ', '--host', '/src/cpython/build/3.7.0/host', '--target', '/src/cpython/installs/python-3.7.0']' returned non-zero exit status 1.
Makefile:5: recipe for target 'all' failed
make[1]: *** [all] Error 1
make[1]: Leaving directory '/src/packages'
Makefile:249: recipe for target 'build/packages.json' failed
make: *** [build/packages.json] Error 2
```
I was trying to put -std=c11 option in Makefile.envs but that didn't change much.
How could I make it work?

**Comment by rth** [comment]
According to their [`setup.py`](https://github.com/MDAnalysis/mdanalysis/blob/8d7d77f45e3de293b27217f75cf5990c1582d9ce/package/setup.py#L369) those C files should compile with `-std=c99`. Though will be used in pyodide. It might be worth double checking that this package can be built on Linux with clang instead of gcc. Maybe it could be worth opening an issue upstream? You could also check if patching their setup.py to use `-std=c11` would help for that specific extension.

Searching https://github.com/emscripten-core/emscripten for compilation errors is also generally helpful, though here I'm not sure it's an issue with emscripten.

**Comment by Hiisi5** [comment]
Clean checkout resolved the issue.
