### ISSUE TITLE
lib2to3import: ModuleNotFoundError: No module named 'pip.req'

### ISSUE THREAD

**Issue by Hiisi5** [iodide-project/pyodide#685]
The package I'm trying to port to pyodide requires lib2to3 module. I'm trying to build it:
```
bin/pyodide mkpkg lib2to3import
make
```
That results in error:
```
./tools/dependency-check.sh
make -C jedi
make[1]: Entering directory '/src/jedi'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/src/jedi'
make -C parso
make[1]: Entering directory '/src/parso'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/src/parso'
make -C packages
make[1]: Entering directory '/src/packages'
# Install build dependencies
/src/cpython/build/3.7.4/host/bin/python3 -m pip install Cython Tempita
Requirement already satisfied: Cython in /src/cpython/build/3.7.4/host/lib/python3.7/site-packages (0.29.19)
Requirement already satisfied: Tempita in /src/cpython/build/3.7.4/host/lib/python3.7/site-packages (0.5.2)
../bin/pyodide buildall . ../build \
	--package_abi=1 --ldflags="-O3 -fopenmp -s "BINARYEN_METHOD='native-wasm'" -Werror -s EMULATED_FUNCTION_POINTERS=1 -s EMULATE_FUNCTION_POINTER_CASTS=1 -s SIDE_MODULE=1 -s WASM=1 -s "BINARYEN_TRAP_MODE='clamp'" --memory-init-file 0 -s LINKABLE=1 -s EXPORT_ALL=1 -s ERROR_ON_MISSING_LIBRARIES=0" --host=/src/cpython/build/3.7.4/host --target=/src/cpython/installs/python-3.7.4 --only 
/src/pyodide_build/common.py:27: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  return yaml.load(fd)
Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    from pip.req import parse_requirements
ModuleNotFoundError: No module named 'pip.req'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/src/pyodide_build/__main__.py", line 32, in <module>
    main()
  File "/src/pyodide_build/__main__.py", line 26, in main
    args.func(args)
  File "/src/pyodide_build/buildall.py", line 117, in main
    build_packages(packagesdir, outputdir, args)
  File "/src/pyodide_build/buildall.py", line 67, in build_packages
    build_package(pkgname, dependencies, packagesdir, outputdir, args)
  File "/src/pyodide_build/buildall.py", line 21, in build_package
    buildpkg.build_package(packagesdir / pkgname / 'meta.yaml', args)
  File "/src/pyodide_build/buildpkg.py", line 210, in build_package
    compile(path, srcpath, pkg, args)
  File "/src/pyodide_build/buildpkg.py", line 122, in compile
    '--target', args.target], env=env, check=True)
  File "/usr/local/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/src/cpython/build/3.7.4/host/bin/python3', '-m', 'pyodide_build', 'pywasmcross', '--cflags', ' ', '--ldflags', '-O3 -fopenmp -s BINARYEN_METHOD=native-wasm -Werror -s EMULATED_FUNCTION_POINTERS=1 -s EMULATE_FUNCTION_POINTER_CASTS=1 -s SIDE_MODULE=1 -s WASM=1 -s BINARYEN_TRAP_MODE=clamp --memory-init-file 0 -s LINKABLE=1 -s EXPORT_ALL=1 -s ERROR_ON_MISSING_LIBRARIES=0 ', '--host', '/src/cpython/build/3.7.4/host', '--target', '/src/cpython/installs/python-3.7.4']' returned non-zero exit status 1.
make[1]: *** [Makefile:5: all] Error 1
make[1]: Leaving directory '/src/packages'
make: *** [Makefile:258: build/packages.json] Error 2
```
I was trying to fix it by installing pip-utils using pip. Yet it didn't help.

**Comment by Hiisi5** [comment]
Unrelated to pyodide. The issue was in setup.py for the package.
