### ISSUE TITLE
buildpkg FileNotFoundErr

### ISSUE THREAD

**Issue by akshara08** [iodide-project/pyodide#690]
Hi,

I'm trying to build pygame package and running into an error because its looking for a file in tools? Any help on fixing this would be highly appreciated. Thanks!

```
`Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/am/PycharmProjects/graph_inference/pyodide/pyodide_build/__main__.py", line 32, in <module>
    main()
  File "/Users/am/PycharmProjects/graph_inference/pyodide/pyodide_build/__main__.py", line 26, in main
    args.func(args)
  File "/Users/am/PycharmProjects/graph_inference/pyodide/pyodide_build/buildpkg.py", line 246, in main
    build_package(path, args)
  File "/Users/am/PycharmProjects/graph_inference/pyodide/pyodide_build/buildpkg.py", line 215, in build_package
    compile(path, srcpath, pkg, args)
  File "/Users/am/PycharmProjects/graph_inference/pyodide/pyodide_build/buildpkg.py", line 127, in compile
    '--target', args.target], env=env, check=True)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/am/PycharmProjects/graph_inference/pyodide/tools/../cpython/build/3.7.4/host/bin/python3': '/Users/am/PycharmProjects/graph_inference/pyodide/tools/../cpython/build/3.7.4/host/bin/python3'`
```

**Comment by akshara08** [comment]
I just used these commands. Is this not right?

```
 pyodide % bin/pyodide mkpkg pygame                                      
 pyodide % bin/pyodide buildpkg packages/pygame/meta.yaml --package_abi 0
```

**Comment by rth** [comment]
Could you try in a docker container?
```
bin/pyodide mkpkg pygame
PYODIDE_PACKAGES="pygame" make
```
Currently that fails with, "sdl-config: not found"

<details>

```
WARNING, No "Setup" File Exists, Running "buildconfig/config.py"
Using UNIX configuration...


Hunting dependencies...
/bin/sh: 1: sdl-config: not found
/bin/sh: 1: sdl-config: not found
/bin/sh: 1: sdl-config: not found
WARNING: "sdl-config" failed!
Unable to run "sdl-config". Please make sure a development version of SDL is installed.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/src/pyodide_build/__main__.py", line 32, in <module>
    main()
  File "/src/pyodide_build/__main__.py", line 26, in main
    args.func(args)
  File "/src/pyodide_build/buildall.py", line 117, in main
    build_packages(packagesdir, outputdir, args)
  File "/src/pyodide_build/buildall.py", line 67, in build_packages
    build_package(pkgname, dependencies, packagesdir, outputdir, args)
  File "/src/pyodide_build/buildall.py", line 21, in build_package
    buildpkg.build_package(packagesdir / pkgname / 'meta.yaml', args)
  File "/src/pyodide_build/buildpkg.py", line 210, in build_package
    compile(path, srcpath, pkg, args)
  File "/src/pyodide_build/buildpkg.py", line 122, in compile
    '--target', args.target], env=env, check=True)
  File "/usr/local/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/src/cpython/build/3.7.4/host/bin/python3', '-m', 'pyodide_build', 'pywasmcross', '--cflags', ' ', '--ldflags', '-O3 -s BINARYEN_METHOD=native-wasm -Werror -s EMULATED_FUNCTION_POINTERS=1 -s EMULATE_FUNCTION_POINTER_CASTS=1 -s SIDE_MODULE=1 -s WASM=1 -s BINARYEN_TRAP_MODE=clamp --memory-init-file 0 -s LINKABLE=1 -s EXPORT_ALL=1 -s ERROR_ON_MISSING_LIBRARIES=0 ', '--host', '/src/cpython/build/3.7.4/host', '--target', '/src/cpython/installs/python-3.7.4']' returned non-zero exit status 1.
make[1]: *** [Makefile:5: all] Error 1
make[1]: Leaving directory '/src/packages'
make: *** [Makefile:258: build/packages.json] Error 2
```

</details>

See https://github.com/iodide-project/pyodide/issues/289 for an earlier discussion about porting pygame and how to use SDL from emscripten ports. Pygame would still probably need to be patched to not run `sdl-config` related commands when building for WASM. 

Closing in favor of https://github.com/iodide-project/pyodide/issues/289, don't hesitate to comment there.

**Comment by patrickyyang** [comment]
> Hi,
> 
> I'm trying to build pygame package and running into an error because its looking for a file in tools? Any help on fixing this would be highly appreciated. Thanks!
> 
> ```
> `Traceback (most recent call last):
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/Users/am/PycharmProjects/graph_inference/pyodide/pyodide_build/__main__.py", line 32, in <module>
>     main()
>   File "/Users/am/PycharmProjects/graph_inference/pyodide/pyodide_build/__main__.py", line 26, in main
>     args.func(args)
>   File "/Users/am/PycharmProjects/graph_inference/pyodide/pyodide_build/buildpkg.py", line 246, in main
>     build_package(path, args)
>   File "/Users/am/PycharmProjects/graph_inference/pyodide/pyodide_build/buildpkg.py", line 215, in build_package
>     compile(path, srcpath, pkg, args)
>   File "/Users/am/PycharmProjects/graph_inference/pyodide/pyodide_build/buildpkg.py", line 127, in compile
>     '--target', args.target], env=env, check=True)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 472, in run
>     with Popen(*popenargs, **kwargs) as process:
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 775, in __init__
>     restore_signals, start_new_session)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1522, in _execute_child
>     raise child_exception_type(errno_num, err_msg, err_filename)
> FileNotFoundError: [Errno 2] No such file or directory: '/Users/am/PycharmProjects/graph_inference/pyodide/tools/../cpython/build/3.7.4/host/bin/python3': '/Users/am/PycharmProjects/graph_inference/pyodide/tools/../cpython/build/3.7.4/host/bin/python3'`
> ```

Hi, Did you succeed?
