### ISSUE TITLE
loading sparse arrays 

### ISSUE THREAD

**Issue by galtay** [iodide-project/pyodide#736]
Excellent project! 

I've been attempting to load sparse arrays with `scipy.sparse.load_npz` and noticed that it didn't exist. 

minimal example,

```
<!DOCTYPE html>                                                                                         
<html>                                                                                                  
  <head>                                                                                                
      <script type="text/javascript">                                                                   
          // set the pyodide files URL (packages.json, pyodide.asm.data etc)                            
          window.languagePluginUrl = 'https://pyodide-cdn2.iodide.io/v0.15.0/full/';                    
      </script>                                                                                         
      <script src="https://pyodide-cdn2.iodide.io/v0.15.0/full/pyodide.js"></script>                    
  </head>                                                                                               
  <body>                                                                                                
    Pyodide test page <br>                                                                              
    Open your browser console to see pyodide output                                                     
    <script type="text/javascript">                                                                     
      languagePluginLoader.then(() => {                                                                 
      pyodide.loadPackage(["scipy"]).then(() => {                                                       
      pyodide.runPython(`                                                                               
      import scipy.sparse                                                                               
      print(f"scipy.__version__: {scipy.__version__}")                                                  
      print(scipy.sparse.load_npz)                                                                      
      `);});});                                                                                         
    </script>                                                                                           
  </body>                                                                                               
</html> 
```

error,

```
Uncaught (in promise) Error: Traceback (most recent call last):
  File "/lib/python3.7/site-packages/pyodide.py", line 45, in eval_code
    return eval(compile(expr, '<eval>', mode='eval'), ns, ns)
  File "<eval>", line 5, in <module>
AttributeError: module 'scipy.sparse' has no attribute 'load_npz'
    _hiwire_throw_error https://pyodide-cdn2.iodide.io/v0.15.0/full/pyodide.asm.js:8
    __runPython https://pyodide-cdn2.iodide.io/v0.15.0/full/pyodide.asm.js:8
    _runPythonInternal https://pyodide-cdn2.iodide.io/v0.15.0/full/pyodide.asm.js:8
    runPython https://pyodide-cdn2.iodide.io/v0.15.0/full/pyodide.asm.js:8
    <anonymous> file:///home/galtay/Sandbox/wikiwhatsthis-pyodide/index.html:19
```

I think I can get around this by writing the CSR sparse matrix components (`data`, `indices`, and `indptr`) to disk using numpy.save and then reading them using numpy.load, but wondering if anyone has found an alternative solution.

**Comment by rth** [comment]
> AttributeError: module 'scipy.sparse' has no attribute 'load_npz'

Yes, that's expected as we still have a somewhat outdated scipy version 0.17 while `scipy.sparse.load_npz` was added in 0.19. We should update it see https://github.com/iodide-project/pyodide/issues/549 

Meanwhile you could probably just copy [that function](https://github.com/scipy/scipy/blob/e777eb9e4a4cd9844629a3c37b3e94902328ad0b/scipy/sparse/_matrix_io.py#L75) into your code as it's relatively short.

**Comment by galtay** [comment]
Thanks for the quick explanation and advice. I must have been reading the 0.19 docs thinking I was reading the 0.17 docs. Looks like scipy uses `np.load` under the hood too.  For now, I'll copy the function over.
