### ISSUE TITLE
Compilations errors when building numpy

### ISSUE THREAD

**Issue by rth** [iodide-project/pyodide#92]
When building numpy locally on Linux (Gentoo) with Python 3.6, I am getting a few compilation errors, seemingly due to missing header files,

1. 
```
C compiler: cc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC

compile options: '-Inumpy/core/src/private -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/home/rth/src/pyodide/cpython/build/3.6.4/host/include/python3.6m -c'
cc: _configtest.c
_configtest.c:1:21: fatal error: xlocale.h: No such file or directory
 #include <xlocale.h>
                     ^
compilation terminated.
[..]
failure.
removing: _configtest.c _configtest.o
```

2.
```
C compiler: cc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC

compile options: '-Inumpy/core/src/private -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/home/rth/src/pyodide/cpython/build/3.6.4/host/include/python3.6m -c'
cc: _configtest.c
_configtest.c:1:24: fatal error: sys/endian.h: No such file or directory
 #include <sys/endian.h>
                        ^
compilation terminated.
```

and some linking issues
```
/home/rth/src/pyodide/packages/numpy/build/numpy-1.14.1/_configtest.c:6: undefined reference to `exp'
collect2: error: ld returned 1 exit status
```

Finally the build exits with,
```pytb
Installed /home/rth/src/pyodide/cpython/build/3.6.4/host/lib/python3.6/site-packages/numpy-1.14.1-py3.6-linux-x86_64.egg
Processing dependencies for numpy==1.14.1
Finished processing dependencies for numpy==1.14.1
emcc -include math.h -I../../config -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/rth/src/pyodide/cpython/installs/python-3.6.4/include -c /tmp/tmppjksnfm2/source.c -o /tmp/tmppjksnfm2/tmp/tmppjksnfm2/source.bc -MMD -MF /tmp/tmppjksnfm2/tmp/tmppjksnfm2/source.o.d
ERROR:root:/tmp/tmppjksnfm2/source.c: No such file or directory ("/tmp/tmppjksnfm2/source.c" was expected to be an input file, based on the commandline arguments provided)
Traceback (most recent call last):
  File "../tools/buildall", line 87, in <module>
    main(args)
  File "../tools/buildall", line 82, in main
    build_packages(packagesdir, args)
  File "../tools/buildall", line 49, in build_packages
    build_package(pkgname, dependencies, packagesdir, args)
  File "../tools/buildall", line 21, in build_package
    build_package(req, dependencies, packagesdir, args)
  File "../tools/buildall", line 26, in build_package
    os.path.join(packagesdir, pkgname, 'meta.yaml'), args)
  File "/home/rth/src/pyodide/tools/buildpkg.py", line 171, in build_package
    compile(path, srcpath, pkg, args)
  File "/home/rth/src/pyodide/tools/buildpkg.py", line 113, in compile
    '--target', args.target], check=True)
  File "/home/rth/.miniconda3/envs/pyodide-env/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/home/rth/src/pyodide/cpython/build/3.6.4/host/bin/python3', '/home/rth/src/pyodide/tools/pywasmcross', '--cflags', ' -include math.h -I../../config', '--ldflags', '-O3 -s BINARYEN_METHOD=native-wasm -Werror -s EMULATED_FUNCTION_POINTERS=1 -s EMULATE_FUNCTION_POINTER_CASTS=1 -s SIDE_MODULE=1 -s WASM=1 --memory-init-file 0 ', '--host', '/home/rth/src/pyodide/cpython/build/3.6.4/host', '--target', '/home/rth/src/pyodide/cpython/installs/python-3.6.4']' returned non-zero exit status 1.
make[1]: *** [Makefile:5: all] Error 1
make[1]: Leaving directory '/home/rth/src/pyodide/packages'
```

See full [numpy-compilation-log.txt](https://github.com/iodide-project/pyodide/files/2228086/numpy-compilation-log.txt) attached. Both header files can be found in `./emsdk/emsdk/emscripten/tag-1.38.4/system/include/` but for some reason the compiler doesn't see them.

This was obtained as a result of running,
```
make -C packages clean
make
```

Please let met know if some additional information would be helpful for debugging.

**Comment by rth** [comment]
Thanks for your reponse! Yes, I have the following includes,
```
% find /usr/include  -iname endian.h                      
/usr/include/winpr2/winpr/endian.h
/usr/include/boost/predef/other/endian.h
/usr/include/bsd/sys/endian.h
/usr/include/endian.h
/usr/include/bits/endian.h
% find /usr/include  -iname xlocale.h
/usr/include/wx-3.0/wx/xlocale.h
/usr/include/X11/Xlocale.h
```
also checked that the used numpy version 1.14.1 builds fine from sources for CPython, so it is able to find those headers.  

Thanks for the suggestions, will investigate further..

**Comment by mdboom** [comment]
Interesting.  None of those files look like they are in the default location where they would be picked up, FWIW.  It's completely possible that numpy is just trying to find these files and the failures are expected.  Does it continue after the first 2 errors, or quit the compilation?  It's quite possible the only real error here is the last one, and might be fixed by the suggested tweak to `pywasmcross`.

Does Numpy compile with the native compiler that pyodide builds?  (in `cpython/build/3.6.4/host/bin/`)  That's the one used by pyodide (not your system python or conda python etc.) so that the version and configuration matches exactly what we're building on the WebAssembly side.

**Comment by rth** [comment]
> Does it continue after the first 2 errors, or quit the compilation? It's quite possible the only real error here is the last one, and might be fixed by the suggested tweak to pywasmcross.

Yes, you are right, the first 2 errors appear to be non critical and don't stop the compilation. I also get those when building numpy for CPython.

As to the last error, it should be fixed in https://github.com/iodide-project/pyodide/pull/94
